"""
This type stub file was generated by pyright.
"""

_MAPPING_CACHE_NAME = ...
class FieldNotFound(Exception):
    ...


class ProtocolMappingNotInitialized(Exception):
    ...


class _EkFieldMapping:
    def __init__(self) -> None:
        ...
    
    def load_mapping(self, tshark_version, tshark_path=...): # -> None:
        ...
    
    def cast_field_value(self, protocol, field_name, field_value): # -> list[list[Any] | Any | str | int | bytes | float] | str | int | bytes | float:
        """Casts the field value to its proper type according to the mapping"""
        ...
    
    def get_field_type(self, protocol, field_name): # -> type[str] | type[int] | type[float] | type[bytes]:
        """Gets the Python type for the given field (only for EK fields).

        If we are unfamiliar with the type, str will be returned.
        """
        ...
    
    def clear(self): # -> None:
        ...
    


MAPPING = ...
