"""
This type stub file was generated by pyright.
"""

import typing
from pyshark.packet import common

DATA_LAYER_NAME = ...
class BaseLayer(common.SlotsPickleable):
    """An object representing a Packet layer."""
    __slots__ = ...
    def __init__(self, layer_name) -> None:
        ...
    
    def get_field(self, name):
        ...
    
    @property
    def field_names(self) -> typing.List[str]:
        """Gets all XML field names of this layer."""
        ...
    
    def has_field(self, name): # -> bool:
        ...
    
    @property
    def layer_name(self): # -> Any:
        ...
    
    def get(self, item, default=...): # -> Any | None:
        """Gets a field in the layer, or the default if not found.

        Works the same way as getattr, but returns the given default if not the field was not found"""
        ...
    
    def __dir__(self): # -> list[str]:
        ...
    
    def __getattr__(self, item):
        ...
    
    def pretty_print(self, writer=...): # -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    


