"""
This type stub file was generated by pyright.
"""

import abc
import typing
from pyshark.packet.layers.base import BaseLayer

class _EkLayerHelperFuncsMixin(abc.ABC):
    """For methods shared between the EK layer and sublayers"""
    def get_field_as_list(self, name) -> list:
        """Helper function to get a certain field always as a list.

        Some fields may appear once or more in the packet. The field will appear as a list if it appears more
        than once. In order to avoid checking certain fields if they're lists or not, this function will
        return the field inside a list at all times.

        For example, in a DNS packet there may be one or more responses.
        A packet with with one response (www.google.com) will return:
            >>> print(pkt.dns.resp_name)
            "www.google.com"
        While a packet with two responses will return:
            >>> print(pkt.dns.resp_name)
            ["www.google.com", "www.google2.com"]

        To avoid this changing behaviour, use:
            >>> print(pkt.dns.get_field_as_list("resp_name"))
            ["www.google.com"]
        """
        ...
    


class EkLayer(BaseLayer, _EkLayerHelperFuncsMixin):
    __slots__ = ...
    def __init__(self, layer_name, layer_dict) -> None:
        ...
    
    def get_field(self, name) -> typing.Union[EkMultiField, None, str, int, bool, bytes, list]:
        ...
    
    def has_field(self, name) -> bool:
        """Checks if the field exists, either a nested field or a regular field"""
        ...
    
    @property
    def field_names(self): # -> list[Any]:
        ...
    
    @property
    def all_field_names(self): # -> list[Any]:
        """Gets all field names, including subfields"""
        ...
    


class EkMultiField(_EkLayerHelperFuncsMixin):
    __slots__ = ...
    def __init__(self, containing_layer: EkLayer, all_fields, full_name, value=...) -> None:
        ...
    
    def get_field(self, field_name): # -> EkMultiField | str | int | bool | bytes | list[Any] | None:
        ...
    
    @property
    def subfields(self): # -> list[Any]:
        ...
    
    @property
    def field_name(self):
        ...
    
    def __getattr__(self, item): # -> EkMultiField | str | int | bool | bytes | list[Any]:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __dir__(self) -> typing.Iterable[str]:
        ...
    


