"""
This type stub file was generated by pyright.
"""

from pyshark.packet.layers.base import BaseLayer

class JsonLayer(BaseLayer):
    __slots__ = ...
    def __init__(self, layer_name, layer_dict, full_name=..., is_intermediate=...) -> None:
        """Creates a JsonLayer. All sublayers and fields are created lazily later."""
        ...
    
    def get_field(self, name): # -> JsonLayer | list[JsonLayer | list[Any] | LayerFieldsContainer] | LayerFieldsContainer:
        """Gets a field by its full or partial name."""
        ...
    
    @property
    def field_names(self): # -> list[Any]:
        ...
    
    def has_field(self, dotted_name) -> bool:
        """Checks whether the layer has the given field name.

        Can get a dotted name, i.e. layer.sublayer.subsublayer.field
        """
        ...
    


