"""
This type stub file was generated by pyright.
"""

import typing
from pyshark.packet.fields import LayerFieldsContainer
from pyshark.packet.layers import base

class XmlLayer(base.BaseLayer):
    __slots__ = ...
    def __init__(self, xml_obj=..., raw_mode=...) -> None:
        ...
    
    def get_field(self, name) -> typing.Union[LayerFieldsContainer, None]:
        """Gets the XML field object of the given name."""
        ...
    
    def get_field_value(self, name, raw=...) -> typing.Union[LayerFieldsContainer, None]:
        """Tries getting the value of the given field.

        Tries it in the following order: show (standard nice display), value (raw value),
        showname (extended nice display).

        :param name: The name of the field
        :param raw: Only return raw value
        :return: str of value
        """
        ...
    
    @property
    def field_names(self) -> typing.List[str]:
        """Gets all XML field names of this layer."""
        ...
    
    @property
    def layer_name(self): # -> Any | Literal['DATA']:
        ...
    
    def __getattr__(self, item): # -> Any | LayerFieldsContainer:
        ...
    
    def get_field_by_showname(self, showname) -> typing.Union[LayerFieldsContainer, None]:
        """Gets a field by its "showname"
        This is the name that appears in Wireshark's detailed display i.e. in 'User-Agent: Mozilla...',
        'User-Agent' is the .showname
        Returns None if not found.
        """
        ...
    


