site_name: Praetor
theme:
  name: readthedocs
  color_mode: dark


nav:
  - Home: index.md
  - API Reference:
    - Praetor: api/praetor.md

plugins:
  - search
  - include-markdown:
      opening_tag: "{!"
      closing_tag: "!}"
  - mkdocstrings:
        handlers:
          python:
            paths: ["src/praetor/"]

markdown_extensions:
  - admonition
