site_name: {{cookiecutter.project_name}}
theme:
  name: readthedocs
  color_mode: dark


nav:
  - Home: index.md
  - API: api.md

plugins:
  - search
  - include-markdown
  - mkdocstrings:
        handlers:
          python:
            paths: ["src/{{cookiecutter.project_slug}}/"]

markdown_extensions:
  - admonition
