"""
This type stub file was generated by pyright.
"""

"""Module used for the actual running of TShark"""
class TSharkNotFoundException(Exception):
    ...


class TSharkVersionException(Exception):
    ...


_TSHARK_INTERFACE_ALIAS_PATTERN = ...
def get_process_path(tshark_path=..., process_name=...):
    """Finds the path of the tshark executable.

    If the user has provided a path
    or specified a location in config.ini it will be used. Otherwise default
    locations will be searched.

    :param tshark_path: Path of the tshark binary
    :raises TSharkNotFoundException in case TShark is not found in any location.
    """
    ...

def get_tshark_version(tshark_path=...): # -> Version:
    ...

def tshark_supports_duplicate_keys(tshark_version):
    ...

def tshark_supports_json(tshark_version):
    ...

def get_tshark_display_filter_flag(tshark_version): # -> Literal['-Y', '-R']:
    """Returns '-Y' for tshark versions >= 1.10.0 and '-R' for older versions."""
    ...

def get_tshark_interfaces(tshark_path=...): # -> list[str]:
    """Returns a list of interface numbers from the output tshark -D.

    Used internally to capture on multiple interfaces.
    """
    ...

def get_all_tshark_interfaces_names(tshark_path=...): # -> list[Any]:
    """Returns a list of all possible interface names. Some interfaces may have aliases"""
    ...

def get_ek_field_mapping(tshark_path=...): # -> Any:
    ...

