"""
This type stub file was generated by pyright.
"""

class BaseTsharkOutputParser:
    DEFAULT_BATCH_SIZE = ...
    async def get_packets_from_stream(self, stream, existing_data, got_first_packet=...): # -> tuple[Any, Any] | tuple[None, Any]:
        """A coroutine which returns a single packet if it can be read from the given StreamReader.

        :return a tuple of (packet, remaining_data). The packet will be None if there was not enough XML data to create
        a packet. remaining_data is the leftover data which was not enough to create a packet from.
        :raises EOFError if EOF was reached.
        """
        ...
    


