"""
This type stub file was generated by pyright.
"""

from pyshark.tshark.output_parser.base_parser import BaseTsharkOutputParser

USE_UJSON = ...
_ENCODED_OS_LINESEP = ...
class TsharkEkJsonParser(BaseTsharkOutputParser):
    ...


def packet_from_ek_packet(json_pkt): # -> Packet:
    ...

