"""
This type stub file was generated by pyright.
"""

from pyshark.tshark.output_parser.base_parser import BaseTsharkOutputParser

USE_UJSON = ...
class TsharkJsonParser(BaseTsharkOutputParser):
    def __init__(self, tshark_version=...) -> None:
        ...
    


def duplicate_object_hook(ordered_pairs): # -> dict[Any, Any]:
    """Make lists out of duplicate keys."""
    ...

def packet_from_json_packet(json_pkt, deduplicate_fields=...): # -> Packet:
    """Creates a Pyshark Packet from a tshark json single packet.

    Before tshark 2.6, there could be duplicate keys in a packet json, which creates the need for
    deduplication and slows it down significantly.
    """
    ...

