"""
This type stub file was generated by pyright.
"""

from pyshark.tshark.output_parser.base_parser import BaseTsharkOutputParser

"""This module contains functions to turn TShark XML parts into Packet objects."""
DEL_BAD_XML_CHARS = ...
class TsharkXmlParser(BaseTsharkOutputParser):
    SUMMARIES_BATCH_SIZE = ...
    def __init__(self, parse_summaries=...) -> None:
        ...
    
    async def get_packets_from_stream(self, stream, existing_data, got_first_packet=...): # -> tuple[Any, Any] | tuple[None, Any]:
        ...
    


def psml_structure_from_xml(psml_structure):
    ...

def packet_from_xml_packet(xml_pkt, psml_structure=...): # -> PacketSummary | Packet:
    """
    Gets a TShark XML packet object or string, and returns a pyshark Packet objec.t

    :param xml_pkt: str or xml object.
    :param psml_structure: a list of the fields in each packet summary in the psml data. If given, packets will
    be returned as a PacketSummary object.
    :return: Packet object.
    """
    ...

