"""
This type stub file was generated by pyright.
"""

import functools
import termcolor

class Pickleable:
    """
    Base class that implements getstate/setstate, since most of the classes are overriding getattr.
    """
    def __getstate__(self): # -> dict[str, Any]:
        ...
    
    def __setstate__(self, data): # -> None:
        ...
    


class SlotsPickleable:
    __slots__ = ...
    def __getstate__(self): # -> dict[Any, Any]:
        ...
    
    def __setstate__(self, data): # -> None:
        ...
    


@functools.wraps(termcolor.colored)
def colored(text, *args, **kwargs): # -> str:
    ...

