"""
This type stub file was generated by pyright.
"""

import typing
from pyshark.packet.common import Pickleable, SlotsPickleable

class LayerField(SlotsPickleable):
    """Holds all data about a field of a layer, both its actual value and its name and nice representation."""
    __slots__ = ...
    def __init__(self, name=..., showname=..., value=..., show=..., hide=..., pos=..., size=..., unmaskedvalue=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def get_default_value(self) -> str:
        """Gets the best 'value' string this field has."""
        ...
    
    @property
    def showname_value(self) -> typing.Union[str, None]:
        """The "pretty value" (as displayed by Wireshark) of the field."""
        ...
    
    @property
    def showname_key(self) -> typing.Union[str, None]:
        """The "pretty name" (as displayed by Wireshark) of the field."""
        ...
    
    @property
    def binary_value(self) -> bytes:
        """Converts this field to binary (assuming it's a binary string)"""
        ...
    
    @property
    def int_value(self) -> int:
        """Returns the int value of this field (assuming it's represented as a decimal integer)."""
        ...
    
    @property
    def hex_value(self) -> int:
        """Returns the int value of this field if it's in base 16

        (either as a normal number or in a "0xFFFF"-style hex value)
        """
        ...
    
    base16_value = ...


class LayerFieldsContainer(str, Pickleable):
    """An object which contains one or more fields (of the same name).

    When accessing member, such as showname, raw_value, etc. the appropriate member of the main (first) field saved
    in this container will be shown.
    """
    def __new__(cls, main_field, *args, **kwargs): # -> Self:
        ...
    
    def __dir__(self): # -> list[str]:
        ...
    
    def add_field(self, field): # -> None:
        ...
    
    @property
    def all_fields(self): # -> Any:
        """Returns all fields in a list, the main field followed by the alternate fields."""
        ...
    
    @property
    def main_field(self): # -> Any:
        ...
    
    @property
    def alternate_fields(self): # -> Any:
        """Return the alternate values of this field containers (non-main ones)."""
        ...
    
    def __getattr__(self, item): # -> Any:
        ...
    


