"""
This type stub file was generated by pyright.
"""

class PacketSummary:
    """A simple object containing a psml summary.

    Can contain various summary information about a packet.
    """
    def __init__(self, structure, values) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def summary_line(self) -> str:
        ...
    


