"""
This type stub file was generated by pyright.
"""

import datetime
import typing
from pyshark.packet.common import Pickleable
from pyshark.packet.layers.base import BaseLayer

class Packet(Pickleable):
    """A packet object which contains layers.

    Layers can be accessed via index or name.
    """
    def __init__(self, layers=..., frame_info=..., number=..., length=..., captured_length=..., sniff_time=..., interface_captured=...) -> None:
        """
        Creates a Packet object with the given layers and info.

        :param layers: A list of BaseLayer objects.
        :param frame_info: Layer object for the entire packet frame (information like frame length, packet number, etc.
        :param length: Length of the actual packet.
        :param captured_length: The length of the packet that was actually captured (could be less then length)
        :param sniff_time: The time the packet was captured (timestamp)
        :param interface_captured: The interface the packet was captured in.
        """
        ...
    
    def __getitem__(self, item):
        """
        Gets a layer according to its index or its name

        :param item: layer index or name
        :return: BaseLayer object.
        """
        ...
    
    def __contains__(self, item): # -> bool:
        """Checks if the layer is inside the packet.

        :param item: name of the layer
        """
        ...
    
    def __dir__(self): # -> list[str]:
        ...
    
    def get_raw_packet(self) -> bytes:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __bool__(self): # -> Literal[True]:
        ...
    
    @property
    def sniff_time(self) -> datetime.datetime:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    def pretty_print(self): # -> None:
        ...
    
    show = ...
    def __getattr__(self, item):
        """
        Allows layers to be retrieved via get attr. For instance: pkt.ip
        """
        ...
    
    @property
    def highest_layer(self) -> BaseLayer:
        ...
    
    @property
    def transport_layer(self) -> BaseLayer:
        ...
    
    def get_multiple_layers(self, layer_name) -> typing.List[BaseLayer]:
        """Returns a list of all the layers in the packet that are of the layer type (an incase-sensitive string).

        This is in order to retrieve layers which appear multiple times in the same packet (i.e. double VLAN)
        which cannot be retrieved by easier means.
        """
        ...
    


