"""
This type stub file was generated by pyright.
"""

import asyncio
import sys
from pyshark.packet.packet import Packet

if sys.version_info < (3, 8):
    ...
else:
    asyncTimeoutError = asyncio.exceptions.TimeoutError
class TSharkCrashException(Exception):
    ...


class UnknownEncyptionStandardException(Exception):
    ...


class RawMustUseJsonException(Exception):
    """If the use_raw argument is True, so should the use_json argument"""
    ...


class StopCapture(Exception):
    """Exception that the user can throw anywhere in packet-handling to stop the capture process."""
    ...


class Capture:
    """Base class for packet captures."""
    SUMMARIES_BATCH_SIZE = ...
    DEFAULT_LOG_LEVEL = ...
    SUPPORTED_ENCRYPTION_STANDARDS = ...
    def __init__(self, display_filter=..., only_summaries=..., eventloop=..., decryption_key=..., encryption_type=..., output_file=..., decode_as=..., disable_protocol=..., tshark_path=..., override_prefs=..., capture_filter=..., use_json=..., include_raw=..., use_ek=..., custom_parameters=..., debug=...) -> None:
        ...
    
    def __getitem__(self, item):
        """Gets the packet in the given index.

        :param item: packet index
        :return: Packet object.
        """
        ...
    
    def __len__(self): # -> int:
        ...
    
    def next(self) -> Packet:
        ...
    
    def next_packet(self) -> Packet:
        ...
    
    def clear(self): # -> None:
        """Empties the capture of any saved packets."""
        ...
    
    def reset(self): # -> None:
        """Starts iterating packets from the first one."""
        ...
    
    def load_packets(self, packet_count=..., timeout=...): # -> None:
        """Reads the packets from the source (cap, interface, etc.) and adds it to the internal list.

        If 0 as the packet_count is given, reads forever

        :param packet_count: The amount of packets to add to the packet list (0 to read forever)
        :param timeout: If given, automatically stops after a given amount of time.
        """
        ...
    
    def set_debug(self, set_to=..., log_level=...): # -> None:
        """Sets the capture to debug mode (or turns it off if specified)."""
        ...
    
    def apply_on_packets(self, callback, timeout=..., packet_count=...): # -> None:
        """Runs through all packets and calls the given callback (a function) with each one as it is read.

        If the capture is infinite (i.e. a live capture), it will run forever, otherwise it will complete after all
        packets have been read.

        Example usage:
        def print_callback(pkt):
            print(pkt)
        capture.apply_on_packets(print_callback)

        If a timeout is given, raises a Timeout error if not complete before the timeout (in seconds)
        """
        ...
    
    async def packets_from_tshark(self, packet_callback, packet_count=..., close_tshark=...): # -> None:
        """
        A coroutine which creates a tshark process, runs the given callback on each packet that is received from it and
        closes the process when it is done.

        Do not use interactively. Can be used in order to insert packets into your own eventloop.
        """
        ...
    
    def close(self): # -> None:
        ...
    
    async def close_async(self): # -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    async def __aenter__(self): # -> Self:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    
    async def __aexit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    
    def get_parameters(self, packet_count=...): # -> list[Any]:
        """Returns the special tshark parameters to be used according to the configuration of this class."""
        ...
    
    def __iter__(self): # -> Iterator[Any] | Generator[Any, Any, None]:
        ...
    
    def __repr__(self): # -> str:
        ...
    


