"""
This type stub file was generated by pyright.
"""

from pyshark.capture.capture import Capture
from pyshark.packet.packet import Packet

class FileCapture(Capture):
    """A class representing a capture read from a file."""
    def __init__(self, input_file=..., keep_packets=..., display_filter=..., only_summaries=..., decryption_key=..., encryption_type=..., decode_as=..., disable_protocol=..., tshark_path=..., override_prefs=..., use_json=..., use_ek=..., output_file=..., include_raw=..., eventloop=..., custom_parameters=..., debug=...) -> None:
        """Creates a packet capture object by reading from file.

        :param keep_packets: Whether to keep packets after reading them via next(). Used to conserve memory when reading
        large caps (can only be used along with the "lazy" option!)
        :param input_file: File path of the capture (PCAP, PCAPNG)
        :param display_filter: A display (wireshark) filter to apply on the cap before reading it.
        :param only_summaries: Only produce packet summaries, much faster but includes very little information.
        :param decryption_key: Optional key used to encrypt and decrypt captured traffic.
        :param encryption_type: Standard of encryption used in captured traffic (must be either 'WEP', 'WPA-PWD', or
        'WPA-PWK'. Defaults to WPA-PWK).
        :param decode_as: A dictionary of {decode_criterion_string: decode_as_protocol} that are used to tell tshark
        to decode protocols in situations it wouldn't usually, for instance {'tcp.port==8888': 'http'} would make
        it attempt to decode any port 8888 traffic as HTTP. See tshark documentation for details.
        :param tshark_path: Path of the tshark binary
        :param override_prefs: A dictionary of tshark preferences to override, {PREFERENCE_NAME: PREFERENCE_VALUE, ...}.
        :param disable_protocol: Tells tshark to remove a dissector for a specific protocol.
        :param use_ek: Uses tshark in EK JSON mode. It is faster than XML but has slightly less data.
        :param use_json: DEPRECATED. Use use_ek instead.
        :param output_file: A string of a file to write every read packet into (useful when filtering).
        :param custom_parameters: A dict of custom parameters to pass to tshark, i.e. {"--param": "value"}
        or else a list of parameters in the format ["--foo", "bar", "--baz", "foo"].
        """
        ...
    
    def next(self) -> Packet:
        """Returns the next packet in the cap.

        If the capture's keep_packets flag is True, will also keep it in the internal packet list.
        """
        ...
    
    def __getitem__(self, packet_index):
        ...
    
    def get_parameters(self, packet_count=...): # -> list[Any]:
        ...
    
    def __repr__(self): # -> str:
        ...
    


