"""
This type stub file was generated by pyright.
"""

from pyshark.capture.capture import Capture

DEFAULT_TIMEOUT = ...
class LinkTypes:
    NULL = ...
    ETHERNET = ...
    IEEE802_5 = ...
    PPP = ...
    IEEE802_11 = ...


class InMemCapture(Capture):
    def __init__(self, bpf_filter=..., display_filter=..., only_summaries=..., decryption_key=..., encryption_type=..., decode_as=..., disable_protocol=..., tshark_path=..., override_prefs=..., use_json=..., use_ek=..., linktype=..., include_raw=..., eventloop=..., custom_parameters=..., debug=...) -> None:
        """Creates a new in-mem capture, a capture capable of receiving binary packets and parsing them using tshark.

        Significantly faster if packets are added in a batch.

        :param bpf_filter: BPF filter to use on packets.
        :param display_filter: Display (wireshark) filter to use.
        :param only_summaries: Only produce packet summaries, much faster but includes very little information
        :param decryption_key: Key used to encrypt and decrypt captured traffic.
        :param encryption_type: Standard of encryption used in captured traffic (must be either 'WEP', 'WPA-PWD',
        or 'WPA-PWK'. Defaults to WPA-PWK).
        :param decode_as: A dictionary of {decode_criterion_string: decode_as_protocol} that are used to tell tshark
        to decode protocols in situations it wouldn't usually, for instance {'tcp.port==8888': 'http'} would make
        it attempt to decode any port 8888 traffic as HTTP. See tshark documentation for details.
        :param tshark_path: Path of the tshark binary
        :param override_prefs: A dictionary of tshark preferences to override, {PREFERENCE_NAME: PREFERENCE_VALUE, ...}.
        :param disable_protocol: Tells tshark to remove a dissector for a specifc protocol.
        :param custom_parameters: A dict of custom parameters to pass to tshark, i.e. {"--param": "value"}
        or else a list of parameters in the format ["--foo", "bar", "--baz", "foo"].
        """
        ...
    
    def get_parameters(self, packet_count=...): # -> list[Any]:
        """Returns the special tshark parameters to be used according to the configuration of this class."""
        ...
    
    def parse_packet(self, binary_packet, sniff_time=..., timeout=...):
        """Parses a single binary packet and returns its parsed version.

        DOES NOT CLOSE tshark. It must be closed manually by calling close() when you're done
        working with it.
        Use parse_packets when parsing multiple packets for faster parsing
        """
        ...
    
    def parse_packets(self, binary_packets, sniff_times=..., timeout=...): # -> list[Any]:
        """Parses binary packets and return a list of parsed packets.

        DOES NOT CLOSE tshark. It must be closed manually by calling close() when you're done
        working with it.
        """
        ...
    
    async def parse_packets_async(self, binary_packets, sniff_times=..., timeout=...): # -> list[Any]:
        """A coroutine which parses binary packets and return a list of parsed packets.

        DOES NOT CLOSE tshark. It must be closed manually by calling close() when you're done
        working with it.
        """
        ...
    
    async def close_async(self): # -> None:
        ...
    
    def feed_packet(self, binary_packet, linktype=..., timeout=...):
        """
        DEPRECATED. Use parse_packet instead.
        This function adds the packet to the packets list, and also closes and reopens tshark for
        each packet.
        ==============

        Gets a binary (string) packet and parses & adds it to this capture.
        Returns the added packet.

        Use feed_packets if you have multiple packets to insert.

        By default, assumes the packet is an ethernet packet. For another link type, supply the linktype argument (most
        can be found in the class LinkTypes)
        """
        ...
    
    def feed_packets(self, binary_packets, linktype=..., timeout=...): # -> list[Any]:
        """Gets a list of binary packets, parses them using tshark and returns their parsed values.

        Keeps the packets in the internal packet list as well.

        By default, assumes the packets are ethernet packets. For another link type, supply the linktype argument (most
        can be found in the class LinkTypes)
        """
        ...
    


