"""
This type stub file was generated by pyright.
"""

from pyshark.capture.capture import Capture

class UnknownInterfaceException(Exception):
    ...


class LiveCapture(Capture):
    """Represents a live capture on a network interface."""
    def __init__(self, interface=..., bpf_filter=..., display_filter=..., only_summaries=..., decryption_key=..., encryption_type=..., output_file=..., decode_as=..., disable_protocol=..., tshark_path=..., override_prefs=..., capture_filter=..., monitor_mode=..., use_json=..., use_ek=..., include_raw=..., eventloop=..., custom_parameters=..., debug=...) -> None:
        """Creates a new live capturer on a given interface. Does not start the actual capture itself.

        :param interface: Name of the interface to sniff on or a list of names (str). If not given, runs on all interfaces.
        :param bpf_filter: BPF filter to use on packets.
        :param display_filter: Display (wireshark) filter to use.
        :param only_summaries: Only produce packet summaries, much faster but includes very little information
        :param decryption_key: Optional key used to encrypt and decrypt captured traffic.
        :param encryption_type: Standard of encryption used in captured traffic (must be either 'WEP', 'WPA-PWD', or
        'WPA-PWK'. Defaults to WPA-PWK).
        :param output_file: Additionally save live captured packets to this file.
        :param decode_as: A dictionary of {decode_criterion_string: decode_as_protocol} that are used to tell tshark
        to decode protocols in situations it wouldn't usually, for instance {'tcp.port==8888': 'http'} would make
        it attempt to decode any port 8888 traffic as HTTP. See tshark documentation for details.
        :param tshark_path: Path of the tshark binary
        :param override_prefs: A dictionary of tshark preferences to override, {PREFERENCE_NAME: PREFERENCE_VALUE, ...}.
        :param capture_filter: Capture (wireshark) filter to use.
        :param disable_protocol: Tells tshark to remove a dissector for a specifc protocol.
        :param use_ek: Uses tshark in EK JSON mode. It is faster than XML but has slightly less data.
        :param use_json: DEPRECATED. Use use_ek instead.
        :param custom_parameters: A dict of custom parameters to pass to tshark, i.e. {"--param": "value"} or
        else a list of parameters in the format ["--foo", "bar", "--baz", "foo"].
        """
        ...
    
    def get_parameters(self, packet_count=...): # -> list[Any]:
        """Returns the special tshark parameters to be used according to the configuration of this class."""
        ...
    
    sniff = ...
    def sniff_continuously(self, packet_count=...): # -> Generator[Any, Any, None]:
        """Captures from the set interface, returning a generator which returns packets continuously.

        Can be used as follows:
        for packet in capture.sniff_continuously():
            print('Woo, another packet:', packet)

        Note: you can also call capture.apply_on_packets(packet_callback) which should have a slight performance boost.

        :param packet_count: an amount of packets to capture, then stop.
        """
        ...
    


